# Generated by Django 5.0.6 on 2024-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='duration',
        ),
        migrations.AlterField(
            model_name='topic',
            name='discription',
            field=models.TextField(verbose_name='Описание темы'),
        ),
    ]
